{*******************************************************************************
 * Initialise le tableau de mois long
 ******************************************************************************}
procedure setLongMonthName ;
begin
    LongMonthNames[1] := 'January' ;
    LongMonthNames[2] := 'Febuary' ;
    LongMonthNames[3] := 'March' ;
    LongMonthNames[4] := 'April' ;
    LongMonthNames[5] := 'May' ;
    LongMonthNames[6] := 'June' ;
    LongMonthNames[7] := 'July' ;
    LongMonthNames[8] := 'August' ;
    LongMonthNames[9] := 'September' ;
    LongMonthNames[10] := 'October' ;
    LongMonthNames[11] := 'November' ;
    LongMonthNames[12] := 'December' ;
end ;