{*******************************************************************************
 * Initialise le tableau de date longue
 ******************************************************************************}
procedure setLongDayName ;
begin
    LongDayNames[1] := 'Sunday' ;
    LongDayNames[2] := 'Monday' ;
    LongDayNames[3] := 'Tuesday' ;
    LongDayNames[4] := 'Wednesday' ;
    LongDayNames[5] := 'Thursday' ;
    LongDayNames[6] := 'Friday' ;
    LongDayNames[7] := 'Saturday' ;
end ;