{*******************************************************************************
 * Initialise le tableau de date courte
 ******************************************************************************}
procedure setShortDayName ;
begin
    ShortDayNames[1] := 'Sun' ;
    ShortDayNames[2] := 'Mon' ;
    ShortDayNames[3] := 'Tue' ;
    ShortDayNames[4] := 'Wed' ;
    ShortDayNames[5] := 'Thu' ;
    ShortDayNames[6] := 'Fri' ;
    ShortDayNames[7] := 'Sat' ;
end ;