{*******************************************************************************
 * Initialise le tableau de mois court
 ******************************************************************************}
procedure setShortMonthName ;
begin
    ShortMonthNames[1] := 'Jan' ;
    ShortMonthNames[2] := 'Feb' ;
    ShortMonthNames[3] := 'Mar' ;
    ShortMonthNames[4] := 'Apr' ;
    ShortMonthNames[5] := 'May' ;
    ShortMonthNames[6] := 'Jun' ;
    ShortMonthNames[7] := 'Jul' ;
    ShortMonthNames[8] := 'Aug' ;
    ShortMonthNames[9] := 'Sep' ;
    ShortMonthNames[10] := 'Oct' ;
    ShortMonthNames[11] := 'Nov' ;
    ShortMonthNames[12] := 'Dec' ;
end ;